### PR TITLE
Change Jakarta Rest master branch to main

### PR DESCRIPTION
**Pull request by jim-krueger**
Please confirm that a default_branch does not need to be specified and that the part history will be preserved.

### CODE REVIEW

**Comment by netomi** [comment]
LGTM, when you dont specify a default branch, "main" will be used as default. The existing master branch will be renamed to main in the process.

**Comment by netomi** [comment]
can a project lead approve that request @spericas ? ty

**Comment by spericas** [comment]
@netomi Approved!

**Comment by netomi** [comment]
changes are live.

**Comment by mkarg** [comment]
Is there a reason why we changed this with just one single voting day?

I am not against the change, but I am against not respecting the fact that other committers want to think over decision for longer than just one day.

**Pull request merged**
